FROM python:3.9-slim
 
# System libs required by OpenCV
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*
 
WORKDIR /code
 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
 
COPY . .
 
RUN chmod -R 777 /code
 
EXPOSE 7860
 
CMD ["python", "app.py"]
 